apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: asvinwin123/k8-node
      context: backend
      sync:
        "*.js": .
deploy:
  kubectl:
    manifests:
      - "app/k8s/**"
