apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort # remove if using ClusterIp
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32002
  selector:
    app: mysql
  # clusterIp: none # uncomment if using ClusterIp
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: test
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
          #hostPath:
          #path: /pathonhost/
          #type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE `students` (`rollNo` int(11) NOT NULL, `name` varchar(255) DEFAULT NULL, PRIMARY KEY (`rollNo`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    INSERT INTO `students` VALUES (1130328,'Varun Kumar');
    INSERT INTO `students` VALUES (1130329,'Asvin Kumar');
    INSERT INTO `students` VALUES (1130330,'Vinoth');
    INSERT INTO `students` VALUES (1130331,'Divya Menon');
